alter table if exists public.telegram_copytrade_executions
  add column if not exists observed_signature text null,
  add column if not exists target_observed_to_submit_ms integer null,
  add column if not exists target_blocktime_to_submit_ms integer null,
  add column if not exists build_ms integer null,
  add column if not exists send_ms integer null,
  add column if not exists winner_provider text null,
  add column if not exists send_rpc_winner text null,
  add column if not exists send_rpc_count integer null,
  add column if not exists target_slot bigint null,
  add column if not exists copy_slot bigint null,
  add column if not exists slot_delta integer null,
  add column if not exists latency_status text null,
  add column if not exists latency_summary jsonb null;

update public.telegram_copytrade_executions
set observed_signature = observed_trade->>'signature'
where observed_signature is null
  and observed_trade ? 'signature';

create index if not exists telegram_copytrade_executions_created_at_desc_idx
  on public.telegram_copytrade_executions(created_at desc);

create index if not exists telegram_copytrade_executions_observed_signature_idx
  on public.telegram_copytrade_executions(observed_signature)
  where observed_signature is not null;

create index if not exists telegram_copytrade_executions_target_observed_latency_idx
  on public.telegram_copytrade_executions(target_observed_to_submit_ms)
  where target_observed_to_submit_ms is not null;

create index if not exists telegram_copytrade_executions_blocktime_latency_idx
  on public.telegram_copytrade_executions(target_blocktime_to_submit_ms)
  where target_blocktime_to_submit_ms is not null;

create index if not exists telegram_copytrade_executions_winner_created_idx
  on public.telegram_copytrade_executions(winner_provider, created_at desc);

create index if not exists telegram_copytrade_executions_mint_created_idx
  on public.telegram_copytrade_executions(mint, created_at desc);

create table if not exists public.latency_admin_users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid null references auth.users(id) on delete cascade,
  email text not null,
  created_at timestamptz not null default now(),
  created_by text null,
  constraint latency_admin_users_email_not_blank check (length(trim(email)) > 0)
);

create unique index if not exists latency_admin_users_email_lower_idx
  on public.latency_admin_users(lower(email));

create unique index if not exists latency_admin_users_auth_user_id_idx
  on public.latency_admin_users(auth_user_id)
  where auth_user_id is not null;

alter table public.latency_admin_users enable row level security;

drop policy if exists "Latency admins can view their own admin row." on public.latency_admin_users;
create policy "Latency admins can view their own admin row."
  on public.latency_admin_users
  for select
  to authenticated
  using (
    auth_user_id is not null
    and (select auth.uid()) = auth_user_id
  );
