create table if not exists public.telegram_cashback_ledger (
  id bigint generated by default as identity primary key,
  chat_id text not null references public.telegram_subscribers(chat_id) on delete cascade,
  trading_wallet_public_key text not null,
  execution_key text not null,
  source_signature text null,
  execution_signature text null,
  action text not null check (action in ('buy', 'sell')),
  platform_fee_lamports bigint not null check (platform_fee_lamports >= 0),
  cashback_lamports bigint not null check (cashback_lamports >= 0),
  status text not null default 'pending' check (status in ('pending', 'claimable', 'paid', 'voided')),
  payout_id bigint null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (execution_key)
);

create table if not exists public.telegram_cashback_payouts (
  id bigint generated by default as identity primary key,
  chat_id text not null references public.telegram_subscribers(chat_id) on delete cascade,
  trading_wallet_public_key text not null,
  amount_lamports bigint not null check (amount_lamports > 0),
  status text not null default 'pending' check (status in ('pending', 'submitted', 'confirmed', 'failed')),
  signature text null,
  error_text text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.telegram_cashback_ledger
  add constraint telegram_cashback_ledger_payout_id_fkey
  foreign key (payout_id)
  references public.telegram_cashback_payouts(id)
  on delete set null;

create index if not exists telegram_cashback_ledger_chat_wallet_status_idx
  on public.telegram_cashback_ledger(chat_id, trading_wallet_public_key, status);

create index if not exists telegram_cashback_ledger_execution_signature_idx
  on public.telegram_cashback_ledger(execution_signature)
  where execution_signature is not null;

create index if not exists telegram_cashback_payouts_chat_wallet_created_at_idx
  on public.telegram_cashback_payouts(chat_id, trading_wallet_public_key, created_at desc);

create unique index if not exists telegram_cashback_payouts_open_wallet_idx
  on public.telegram_cashback_payouts(chat_id, trading_wallet_public_key)
  where status in ('pending', 'submitted');

alter table public.telegram_cashback_ledger enable row level security;
alter table public.telegram_cashback_payouts enable row level security;

grant select, insert, update, delete on public.telegram_cashback_ledger to service_role;
grant select, insert, update, delete on public.telegram_cashback_payouts to service_role;
grant usage, select on sequence public.telegram_cashback_ledger_id_seq to service_role;
grant usage, select on sequence public.telegram_cashback_payouts_id_seq to service_role;

notify pgrst, 'reload schema';
