create table if not exists public.telegram_copytrade_executions (
  id bigint generated by default as identity primary key,
  chat_id text not null references public.telegram_subscribers(chat_id) on delete cascade,
  source_wallet_address text not null,
  source_wallet_label text null,
  trading_wallet_public_key text not null,
  mint text not null,
  action text not null check (action in ('buy', 'sell')),
  amount text not null,
  denominated_in_sol boolean not null,
  status text not null check (status in ('submitted', 'failed')),
  signature text null,
  error_text text null,
  http_status integer null,
  observed_trade jsonb not null,
  request jsonb not null,
  response jsonb null,
  trailing_sell_step_index integer null,
  trailing_sell_total_steps integer null,
  created_at timestamptz not null default now()
);

create index if not exists telegram_copytrade_executions_chat_id_created_at_idx
  on public.telegram_copytrade_executions(chat_id, created_at desc);

create index if not exists telegram_copytrade_executions_source_wallet_idx
  on public.telegram_copytrade_executions(source_wallet_address);

create index if not exists telegram_copytrade_executions_mint_idx
  on public.telegram_copytrade_executions(mint);

create unique index if not exists telegram_copytrade_executions_signature_step_idx
  on public.telegram_copytrade_executions(
    chat_id,
    action,
    signature,
    coalesce(trailing_sell_step_index, -1),
    coalesce(trailing_sell_total_steps, -1)
  )
  where signature is not null;

alter table public.telegram_copytrade_executions enable row level security;
